####################################################
# Configuration Properties about Datasource
####################################################
spring:
  datasource:
    type: "com.alibaba.druid.pool.DruidDataSource"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/supervision-system?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=true&zeroDateTimeBehavior=convertToNull"
    username: "root"
    password: "123456"
    druid:
      initial-size: 30
      min-idle: 30
      max-active: 200
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 1000000
      validation-query: "SELECT 1 FROM DUAL"
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: "druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500"
      filter:
        stat:
          enabled: true
        wall:
          enabled: true
